[package]
name = "portfolio"
version = "0.1.0"
authors = ["KRTirtho <krtirtho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.15"
termion = "1.5"